name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Compiler (g++)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile Tests
      run: |
        cd week1
        g++ -g -Wall -Wextra -Werror main.cpp functions.s -o test_run

    - name: Execute Catch2 Unit Tests
      run: |
        cd week1
        ./test_run