name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Cross-Compiler and QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-aarch64-linux-gnu qemu-user

    - name: Compile Tests (ARM64)
      run: |
        cd week1
        aarch64-linux-gnu-g++ -g -Wall -Wextra -Werror main.cpp functions.s -o test_run

    - name: Execute Catch2 Unit Tests (via Emulator)
      run: |
        cd week1
        qemu-aarch64 -L /usr/aarch64-linux-gnu ./test_run